import { Space_Grotesk } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';
import Providers from '@/context/Providers';
const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['500'],
  variable: '--font-space-grotesk',
  display: 'swap',
});

export const metadata = {
  title: 'CNLA',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <NavBar />
        <Providers>
          <main>{children}</main>
        </Providers>

        <Footer />
      </body>
    </html>
  );
}
